name: Pull request workflow
on: pull_request

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.wbrawner.com/actions/checkout@v6
      - uses: https://git.wbrawner.com/actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle Wrapper
        uses: https://git.wbrawner.com/gradle/actions/wrapper-validation@2b9247147a6efbddfece21c734c99ddc4c696eee
      - name: Setup Gradle
        uses: https://git.wbrawner.com/gradle/actions/setup-gradle@2b9247147a6efbddfece21c734c99ddc4c696eee
      - name: Run Unit Tests
        run: ./gradlew --no-daemon --stacktrace check
      - name: Publish JUnit Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Unit Test Results
          path: "*/build/test-results/test/*.xml"
          if-no-files-found: error
