name: Pull request workflow
on: pull_request

jobs:
  test:
    name: Build and Test
    runs-on: docker
    container:
      image: git.wbrawner.com/wbrawner/docker/java:21
    steps:
      - uses: https://git.wbrawner.com/actions/checkout@v6
      - name: Run Unit Tests
        run: ./gradlew --no-daemon --stacktrace check
      - name: Publish JUnit Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Unit Test Results
          path: "*/build/test-results/test/*.xml"
          if-no-files-found: error
