name: Pull request workflow
on: pull_request

permissions:
  statuses: write
  checks: write

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --stacktrace build
      - name: Publish JUnit Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Unit Tests
          path: "*/build/test-results/test/*.xml"
          reporter: java-junit
          fail-on-error: true
